//------------------------------------------------------------------------------
// <auto-generated>
// This code is generated by tools.
// Running version: 4.0.30319.42000
//
// The change of this document may cause incorrect behavior, if
// Re -generate the code, the change will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilibiliSubtitle2SRT.Properties
{


    /// <summary>
    /// Strongly typed resource class, used to find localized strings, etc.
    /// </summary>
    // This class is created by StronglyTypedResourceBuilder
    // Classes are automatically generated by tools like ResGen or Visual Studio.
    // To add or remove members, edit the .ResX file and re-run ResGen
    // (with /str as command option), or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BilibiliSubtitle2SRT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Override the CurrentUICulture property of the current thread
        /// Resource lookup using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
