name: Bilibili-to-srt build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
    
      - name: Nuget Restore
        run: nuget restore
      
      - name: Build .Net472
        run: msbuild /p:Configuration=Release /p:TargetFramework=net472 /verbosity:minimal

      - name: Upload .Net472 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssetStudio.net472
          path: AssetStudioGUI/bin/Release/net472
